apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-28T05:03:21Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3217"
  uid: c77a321e-71bc-4a2a-aa42-26f3de2d62b0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.214.99
  clusterIPs:
  - 10.104.214.99
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31374
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
